# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Giles Dring
email: ""
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my personal website. Who am I again?

twitter_username: gilesdring
github_username:  gilesdring
permalink: /blog/:year/:month/:day/:slug/

google_analytics: UA-26168408-1

show_downloads: false

github:
  is_project_page: false
  is_user_page: false

remote_theme: dringtech/jekyll-theme-barebones

# Build settings
markdown: kramdown

paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

collections:
  projects:
    output: true
  redirects:
    output: true
  inspirations:
    output: false

  # - music
