backend:
  name: github
  repo: gilesdring/gilesdring.github.io
  base_url: https://j5do03xkk8.execute-api.eu-west-2.amazonaws.com
  auth_endpoint: prod/auth  

media_folder: images/uploads

collections:
  - name: posts
    description: Blog posts
    label: Posts
    label_singular: Post
    folder: _posts/
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{year}}-{{month}}-{{day}}_{{title}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - label: Publish Date
        name: date
        widget: datetime
        format: "YYYY-MM-DD HH:mm:ss Z"
        dateFormat: LL
        timeFormat: "HH:mm"
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
